Development
Kwamay/News_App pull request #3
Opened 2023-10-27 16:13 UTC by Kwamay

In this module I...........

-[ ] Fetch an API data from a NewApp to my project

-[ ] Run a unit test using react library for the component created

-[ ] Styled the project per the project requirement

2023-10-27 17:18 UTC, Alusp requested changes
Hi @Kwamay, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![close](https://media.giphy.com/media/nJKDTpuxnZE7fb6Z1b/giphy.gif)

## Highlights

- [ ] Use Professional Readme file 👍
- [ ] Descriptive PR Summary used 👍
- [ ]  Use React components.👍
- [ ] Handle events in a React app. 👍
- [ ] Use store, actions, and reducers in React. 👍


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alusp in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-27 17:18 UTC, Alusp commented on README.md
> +- [Live Demo]()
- [ ] Good job so far, :clap: , However, Please ensure that you add a live demo version of your App, currently you do not have it. :slightly_smiling_face:

2023-10-27 17:18 UTC, Alusp commented on README.md
> +- [Video Presentation](https://www.loom.com/share/03dde572f79041519a2f15be5b913f06?sid=36d18937-ac9b-451d-bc27-f567d3df258d)
- [ ] Please ensure that you mention a piece of code you are most proud of in your video presentation. :slightly_smiling_face:

2023-10-27 17:18 UTC, Alusp commented on src/component/Nav.jsx
> +    </Link>
- [ ] According to the project requirement, the back button is supposed to be displayed only on the details page and not on the Home page, Please resolve that. :slightly_smiling_face: 
- ![backbtnOnHome](https://github.com/Kwamay/News_App/assets/43528594/8299b8fb-3896-4b6d-bc0e-48f62947d476)

2023-10-27 17:18 UTC, Alusp commented on src/component/Details.jsx
> +          </li>
- [x] Your details page images are stretched out, which destroys the look and feel of your design, Please ensure that you style them accordingly. 
- ![DetailsStretched](https://github.com/Kwamay/News_App/assets/43528594/12a748ec-d212-4b15-a349-2fe57bd8fbdc)

- [x] Please ensure that you use the `lato` and `gill sans` fonts family given in the design requirement.
- [x] And please make sure you Layout: composition and space between elements in your details page.

2023-10-28 00:05 UTC, ademibowale approved these changes
Hi @Kwamay  , 


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️
- Use functional components✔️
- follow the [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs))✔️
- The project contains a `Home` page and a `Detail` page✔️
- The category item detail page has its unique route within the SPA.
- Descriptive commit messages ✔️ 
- App has unit tests for several components of the app
- Good use of Github flow ✔️

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)




- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-28 20:47 UTC, merged